// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ0vt77XbPpxfmIiAubIGgEJwadUY9-VU',
    appId: '1:451622851524:web:09ea230412a13eefd98a91',
    messagingSenderId: '451622851524',
    projectId: 'reminder-96538',
    authDomain: 'reminder-96538.firebaseapp.com',
    storageBucket: 'reminder-96538.appspot.com',
    measurementId: 'G-H8VTQ03SVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB22GKhWXYAW5VDOPpRuXgeEKM8lIuy3HQ',
    appId: '1:451622851524:android:882ecbb6e8a43232d98a91',
    messagingSenderId: '451622851524',
    projectId: 'reminder-96538',
    storageBucket: 'reminder-96538.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC_LiKy4aaHYDJynMXlTGu5XJfEaJIQ7M',
    appId: '1:451622851524:ios:b82937ff26f09e08d98a91',
    messagingSenderId: '451622851524',
    projectId: 'reminder-96538',
    storageBucket: 'reminder-96538.appspot.com',
    iosBundleId: 'com.example.reminderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC_LiKy4aaHYDJynMXlTGu5XJfEaJIQ7M',
    appId: '1:451622851524:ios:fc76fbe0b34c16a2d98a91',
    messagingSenderId: '451622851524',
    projectId: 'reminder-96538',
    storageBucket: 'reminder-96538.appspot.com',
    iosBundleId: 'com.example.reminderApp.RunnerTests',
  );
}
